export const data = [
  {
    id: 1,
    heading: "Beach Pirate.",
    subheading: "Mystiroius chractor find onthe ombabas",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia, asperiores quod veritatis placeat",
    background: "#FFFBDA",
    color: "#FFBB70",
    pallet: "#DC6B19",
    logo: "#FFAF45",
    model: {
      pose: 0,
      jacket: "#E4C59E",
      pants: "#DD5746",
      beard: "#D862BC",
      eyes: "#15F5BA",
    },
  },
  {
    id: 2,
    heading: "Sky Pirate.",
    subheading: "Mystiroius nerd flowing in skys",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia, asperiores quod veritatis placeat",
    background: "#40A2D8",
    color: "#0C2D57",
    pallet: "#1F2544",
    logo: "#0A1D56",
    model: {
      pose: 3,
      jacket: "#3C0753",
      pants: "#F6D6D6",
      beard: "#A1EEBD",
      eyes: "#7071E8",
    },
  },
  {
    id: 3,
    heading: "M.De.Luffy",
    subheading: "King of pirates",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente officia, asperiores quod veritatis placeat",
    background: "#BE3144",
    color: "#7D0A0A",
    pallet: "#E72929",
    logo: "#F0EDD4",
    model: {
      pose: 2,
      jacket: "#B31312",
      pants: "#0766AD",
      beard: "#F6C56B",
      eyes: "#FDF7E4",
    },
  },
];
